### ISSUE TITLE
on-off control

### ISSUE THREAD

**Issue by sadegroo** [mule1972/NeoPixelBLVmgn#1]
Hi,

It may be a nice feature to include support for an on-off button in the code.
1 of the 2 spare buttons on the front panel could be used. (momentary or latching selectable ?)
It feels like a waste to have them on when I'm not around.

**Comment by sadegroo** [comment]
I implemented the feature and I'm goint to test it on the printer soon. I used the [Bounce2 library](https://github.com/thomasfredericks/Bounce2) for debouncing of the momentary switch. I'm thinking of adding additional, optional flip-flops to control other pins for relays to switch lights etc.

**Comment by sadegroo** [comment]
@mule1972  feel free to check it out. bb70fb22ce09e448944db8b9816fa989ab2695d2

**Comment by mule1972** [comment]
Thanks for your input and work. Going to test it.

**Comment by wkellyoconnor** [comment]
Is this merged into the master file? I like the Idea as well. I hard wired the button to the 5v supply to the pixels but with the Arduino 3" away from the front buttons it would be very easy to implement.

**Comment by mule1972** [comment]
No, because I believe it is to special and has to be made customizable.
