### ISSUE TITLE
Embeded RGB Led strip control

### ISSUE THREAD

**Issue by titvs** [mule1972/NeoPixelBLVmgn#3]
Hi Claus! 

Im trying to include on your Neopixel code control for a RGB led strip. Was trying to do something fancy, like pink for warming up, white printing, green for printing done, etc. From your code there are already status flags and i tried to put the led color change command on the "switch-case" block but nothing happens. 
The led strip initializes ok since ive put an initial color command (white) on the setup block. Any pointers where i should put the commands to change color or how to approach this? 

Thanks a lot for your work!

**Comment by mule1972** [comment]
Please attach your code so that I can take a look.

**Comment by titvs** [comment]
To not attach the complete code, i added to the beginning:

```
#include <LEDStripDriver.h>

// use two available GPIO pins from your board
// DIN=GPIO16, CIN=GPIO14 in this example
LEDStripDriver led = LEDStripDriver(10, 11);
```

And to void setup():

`led.setColor(255, 255, 255);` 

With this the leds light up with white color. Then i tried to modify the switch block:

```
 switch (Printer.Status)
          {
            case 'I':
              NeoPixelPrinterStat.fill(NeoPixelPrinterStatColorIdle);
              led.setColor(254, 253, 255);
              break;
            case 'P':
              NeoPixelPrinterStat.fill(NeoPixelPrinterStatColorPrinting);
              led.setColor(255, 255, 255);
              break;
            case 'S':
              NeoPixelPrinterStat.fill(NeoPixelPrinterStatColorStopped);
              led.setColor(255, 77, 77);
              break;
            case 'C':
              NeoPixelPrinterStat.fill(NeoPixelPrinterStatColorConfiguring);
              led.setColor(254, 253, 255);
              break;
            case 'A':
              NeoPixelPrinterStat.fill(NeoPixelPrinterStatColorPaused);
              led.setColor(255, 255, 128);
              break;
            case 'D':
              NeoPixelPrinterStat.fill(NeoPixelPrinterStatColorBusy);
              led.setColor(255, 187, 51);
              break;
            case 'R':
              NeoPixelPrinterStat.fill(NeoPixelPrinterStatColorPausing);
              led.setColor(255, 242, 179);
              break;
            case 'B':
              NeoPixelPrinterStat.fill(NeoPixelPrinterStatColorResuming);
              led.setColor(255, 255, 255);
              break;
            case 'F':
              NeoPixelPrinterStat.fill(NeoPixelPrinterStatColorFlashing);
              led.setColor(255, 255, 255);
              break;
            default:
              NeoPixelPrinterStat.fill(NeoPixelPrinterStatColorDefault);
              led.setColor(255, 255, 255);
              break;
```
Each case with its defined color in RGB format. But as i told you, the leds didnt change color, for example, when the status neopixel turns yellow (busy).
I was aiming at something straight forward like putting the instruction `led.setColor(r, g, b)` somewhere in the code were it monitors the printer status.
Isnt it possible to put it on the `void loop()` block and have it change the color based on the printer status? Is this the `Printer.Status` variable?

**Comment by mule1972** [comment]
Am I right that you are using the following lib: [https://github.com/MrKrabat/LED-Strip-Driver-Module](url)?
Printer.Status is the correct variable to fetch the actual printer status. 
Honestly I don't see any issues software wise.
 
You may do another simple test to see if the color change is really working:
In the section "void setup():" simply add some code like:
led.setColor(255, 255, 255);
delay(1000);
led.setColor(255, 0, 0);

**Comment by titvs** [comment]
Thats the lib.  Ok, will do that test and try to implement on the main "loop()" instead.
I have my blv printing, so ill report later :)
Thanks again Claus.

**Comment by lesaux** [comment]
Are you trying this with the rgb led strips that came in aliexpress kit? Did you buy a 12v led driver or use your own mosfets?

**Comment by titvs** [comment]
> Are you trying this with the rgb led strips that came in aliexpress kit? Did you buy a 12v led driver or use your own mosfets?

Yes Lesaux, with the rgb led strip Ben has on the BOM. And yes, i bought a 12v driver:

[https://www.aliexpress.com/item/32786272573.html?spm=a2g0s.9042311.0.0.27424c4dJO7Hkm](https://www.aliexpress.com/item/32786272573.html?spm=a2g0s.9042311.0.0.27424c4dJO7Hkm)

**Comment by lesaux** [comment]
Cool! Thanks! I had the same idea but couldn't decide on a driver yet. Thanks for the link (and more importantly the code!).

**Comment by titvs** [comment]
No problem! But bear in mind that im still troubleshooting it... ;)

**Comment by mule1972** [comment]
@titvs Any further help needed or did you find the cause for the issue?

**Comment by titvs** [comment]
@mule1972 Unfortunnely i didnt have the time to program the code. I hope to do it soon. In the meantime ive added this code to a function to be run at the end of the loop():

```
void ledstriprgbupdate() 
{

  if ( Printer.Status == 'I' ) { led.setColor(255, 250, 240); }  // IDLE 

// HEATUP
if (Printer.HeaterStatusHeatbed == 2 || Printer.HeaterStatusHotend == 2) {
  if (Printer.ActTempHeatbed < Printer.ActiveTempHeatbed || Printer.ActTempHotend < Printer.ActiveTempHotend) {
    led.setColor(255, 76, 66);
  }
}

// if ( Printer.Status == "P" ) { led.setColor(255, 255, 255); }  // PRINTING

if ( Printer.Status == 'S' ) { led.setColor(255, 8, 0); }  // STOPPED
if ( Printer.Status == 'C' ) { led.setColor(93, 173, 236); }  // CONFIGURING
if ( Printer.Status == 'A' ) { led.setColor(255, 239, 0); }  // PAUSED
if ( Printer.Status == 'D' ) { led.setColor(252, 194, 0); }  // BUSY
if ( Printer.Status == 'R' ) { led.setColor(255, 239, 0); }  // PAUSING
if ( Printer.Status == 'B' ) { led.setColor(132, 222, 2); }  // RESUMING
if ( Printer.Status == 'F' ) { led.setColor(0, 72, 186); }  // FLASHING
}
```
The part for the "heat up" isnt working so maybe you can check if the IF conditions are correct.
I need to think of a way to implement the status checking on the main loop() and change the color accordingly...
