### ISSUE TITLE
Generic version for OctoPrint

### ISSUE THREAD

**Issue by tgmorris99** [mule1972/NeoPixelBLVmgn#5]
Wanted to let you know that I heavily modified a version of this to support non PanelDue solutions as I'm building a BLV mgn Cube but using an SKR PRO and RPi with OctoPrint for control. I also included the on/off changes done by sadegroo.

Rather than fork it I opted for a new repository as the front end is very different since it's driven via MQTT. I made a few changes to the NeoPixel logic as I use them to also provide some start up and connection information but the majority of it is unchanged.

The new version can be found at https://github.com/tgmorris99/NeoPixelBLV_MQTT and it should work with any printer that runs OctoPrint so long as it has a WiFi connection and MQTT broker/client installed. I think I've got everything working regardless of the options chosen but welcome any input or additional testing.

I don't do Facebook so can't let them know as Ben set it up as a private group.

**Comment by mule1972** [comment]
Great work! Thanks for the info. If you would like I could post a link on the facebook group to your repository.

**Comment by tgmorris99** [comment]
I really appreciate all the work you did on getting this working reliably and it would be great if you'd post a note on the Facebook group about the OctoPrint implementation.

BTW - I just made a small change to the Printer Stat display so that the pixel representing the currently active percentage is lit in a specific color and also animated.  The color shown is configurable but it's currently shown as the same color as "Done."

How hard would it be to make the "last" animated pixel toggle when it's the only one being animated as well, instead of staying at the "Animation" color?
