### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by celulari** [mule1972/NeoPixelBLVmgn#9]
Recently I've upgraded my paneldue 4.3" from V2 board with firmware 1.23.2 to a V3 board with latest firmware (3.2.9) and the led rings doesn't shows the status anymore. I'm using the latest code on my Arduino (July release?). Swaped to the old board and works again. My Duet Is a Duet 2 WiFi with 3.2 firmware

**Comment by mule1972** [comment]
Please test the newest master version
